package com.myspace.digitalrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class productDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("productName")
	private java.lang.String productName;
	@org.kie.api.definition.type.Label("benefitType")
	private java.lang.String benefitType;
	@org.kie.api.definition.type.Label("hospitalType")
	private java.lang.String hospitalType;
	@org.kie.api.definition.type.Label("membershipType")
	private java.lang.String membershipType;

	@org.kie.api.definition.type.Label("premium")
	private java.lang.Integer premium;

	@org.kie.api.definition.type.Label("salaryBand")
	private String salaryBand;

	@org.kie.api.definition.type.Label("salary")
	private java.lang.Integer salary;

	@org.kie.api.definition.type.Label("sumAssured")
	private java.lang.Integer sumAssured;

	@org.kie.api.definition.type.Label("startDate")
	private java.lang.Long startDate;

	@org.kie.api.definition.type.Label("endDate")
	private java.lang.Long endDate;

	@org.kie.api.definition.type.Label("productOwner")
	private java.lang.String productOwner;

	@org.kie.api.definition.type.Label("lineOfBusiness")
	private java.lang.String lineOfBusiness;

	@org.kie.api.definition.type.Label(value = "scoringFactor")
	private java.lang.Integer scoringFactor;

	public productDetails() {
	}

	public java.lang.String getProductName() {
		return this.productName;
	}

	public void setProductName(java.lang.String productName) {
		this.productName = productName;
	}

	public java.lang.String getBenefitType() {
		return this.benefitType;
	}

	public void setBenefitType(java.lang.String benefitType) {
		this.benefitType = benefitType;
	}

	public java.lang.String getHospitalType() {
		return this.hospitalType;
	}

	public void setHospitalType(java.lang.String hospitalType) {
		this.hospitalType = hospitalType;
	}

	public java.lang.String getMembershipType() {
		return this.membershipType;
	}

	public void setMembershipType(java.lang.String membershipType) {
		this.membershipType = membershipType;
	}

	public java.lang.Integer getPremium() {
		return this.premium;
	}

	public void setPremium(java.lang.Integer premium) {
		this.premium = premium;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public java.lang.String getSalaryBand() {
		return this.salaryBand;
	}

	public void setSalaryBand(java.lang.String salaryBand) {
		this.salaryBand = salaryBand;
	}

	public java.lang.Integer getSumAssured() {
		return this.sumAssured;
	}

	public void setSumAssured(java.lang.Integer sumAssured) {
		this.sumAssured = sumAssured;
	}

	public java.lang.Long getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.lang.Long startDate) {
		this.startDate = startDate;
	}

	public java.lang.Long getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.lang.Long endDate) {
		this.endDate = endDate;
	}

	public java.lang.String getProductOwner() {
		return this.productOwner;
	}

	public void setProductOwner(java.lang.String productOwner) {
		this.productOwner = productOwner;
	}

	public java.lang.String getLineOfBusiness() {
		return this.lineOfBusiness;
	}

	public void setLineOfBusiness(java.lang.String lineOfBusiness) {
		this.lineOfBusiness = lineOfBusiness;
	}

	public java.lang.Integer getScoringFactor() {
		return this.scoringFactor;
	}

	public void setScoringFactor(java.lang.Integer scoringFactor) {
		this.scoringFactor = scoringFactor;
	}

	public productDetails(java.lang.String productName,
			java.lang.String benefitType, java.lang.String hospitalType,
			java.lang.String membershipType, java.lang.Integer premium,
			java.lang.String salaryBand, java.lang.Integer salary,
			java.lang.Integer sumAssured, java.lang.Long startDate,
			java.lang.Long endDate, java.lang.String productOwner,
			java.lang.String lineOfBusiness, java.lang.Integer scoringFactor) {
		this.productName = productName;
		this.benefitType = benefitType;
		this.hospitalType = hospitalType;
		this.membershipType = membershipType;
		this.premium = premium;
		this.salaryBand = salaryBand;
		this.salary = salary;
		this.sumAssured = sumAssured;
		this.startDate = startDate;
		this.endDate = endDate;
		this.productOwner = productOwner;
		this.lineOfBusiness = lineOfBusiness;
		this.scoringFactor = scoringFactor;
	}

}